### ISSUE TITLE
Create incentive scheme calculation v2

### ISSUE THREAD

**Issue by tolbrino** [hoprnet/simulations#1]
We need a framework to calculate changes in our incentive scheme and simulate alternative parameter combinations. This is needed to make better educated decision and devise strategic changes in the incentive scheme.

### Approach

- the framework should be implemented in a Jupyter notebook such that we can interactively play with the data and have in-place visualization

### Questions we want to answer

- What shall be the next min and max limits for our next APY calculation in CT?
- What shall be groups of stakers which receive exceptional handling?
- What is the distribution of stakes in the network currently (end of 01/2024)?
  - This distribution should be used as input for calculating the network-level impact of the new APY calculation.

### Definition of Done

- [x] The Jupyter notebook has been uploaded to an internal Git repository (private)
- [x] The Jupyter notebook and calculations were reviewed and presented within a small select group
- [x] Add a total budget calculation 
- [x] Show the stake transformation curve along with additional economic model's parameter's widgets.
